tap_hubspot/__init__.py

Solve multiple types issue

---

tap_hubspot/__init__.py

Replace dash to under score

---

tap_hubspot/__init__.py

Do not rebuild schema on each run instead lift schema from catalog

---

tap_hubspot/__init__.py
tap_hubspot/schemas/deal_pipelines.json
tap_hubspot/schemas/deals.json

add hs_lastmodifieddate field

---

tap_hubspot/__init__.py
tap_hubspot/hubspot.py
tap_hubspot/schemas/submissions.json

Get submission data

---

tap_hubspot/hubspot.py

Tap hubspot  unauthorized for url exception

---

tap_hubspot/hubspot.py

Pull events data

---

tap_hubspot/hubspot.py

delete archived false param

---

tap_hubspot/hubspot.py

delete archived false

---

tap_hubspot/hubspot.py

add lifecycle stages to contact fields

---

tap_hubspot/hubspot.py

add latest lifecycle stage to hubspot

---

tap_hubspot/__init__.py

add stacktrace of exception when it occurs

---

tap_hubspot/hubspot.py
tap_hubspot/stream.py

fix issue with missing stream runs

---

tap_hubspot/hubspot.py

remember to delete response objects

---

tap_hubspot/__init__.py
tap_hubspot/hubspot.py

use shelve as persistence out-of-memory cache for form_guids and contacts_events_ids

---

tap_hubspot/__init__.py
tap_hubspot/hubspot.py

simplify contacts form guid extraction

---

tap_hubspot/hubspot.py

sync shelve

---

tap_hubspot/hubspot.py

include additional emails for contacts

---

tap_hubspot/hubspot.py

add ivalua custom fields

---

tap_hubspot/hubspot.py

add sql_in_date and quote_sent_timestamp to deals properties

---

tap_hubspot/hubspot.py

add qualified_opportunity field as Nick requested

---

tap_hubspot/hubspot.py

use max limit to sync email events faster

---

tap_hubspot/hubspot.py

add converting_touch for ivalua

---

tap_hubspot/hubspot.py

ds-325-trengo-revenue-model

---

tap_hubspot/hubspot.py

Ds-322-investigate-contacts-on-deals

---

tap_hubspot/hubspot.py

adding deal owner information

---

tap_hubspot/hubspot.py

add pixelz custom fields

---

tap_hubspot/hubspot.py

ds-627-add-custom-revenue-field-for-capchase-in

---

tap_hubspot/hubspot.py

capmo revenue model

---

tap_hubspot/hubspot.py

sendcloud revenue model

---

tap_hubspot/hubspot.py

tiers capmo revenue model

---

tap_hubspot/hubspot.py

ds-682-add-pixelz-fields-in-hubspot-tap

---

tap_hubspot/hubspot.py

new custom field humanforce

---

.vscode/launch.json
main.py
tap_hubspot/hubspot.py

de 911 deals

---

tap_hubspot/hubspot.py

de 922 get all fields for deals

---

tap_hubspot/hubspot.py

De 910 contacts

---

tap_hubspot/hubspot.py

Store id's submissions for contacts

---

tap_hubspot/hubspot.py

Reverts dreamdata-io/tap-hubspot#58

Revert "De 899 engagements"

---

tap_hubspot/hubspot.py

https://linear.app/dreamdata/issue/DE-977/tab-hubspot-fix-400-bad-request-on-dealssearch
- 
- 

fix reset pagination variables

---

tap_hubspot/__init__.py
tap_hubspot/hubspot.py

de 1005 hubspot submissions are replacing all

---

tap_hubspot/hubspot.py

De-1008-final-deploy-of-hubspot-v4

---

tap_hubspot/__init__.py
tap_hubspot/hubspot.py

De 976 does contactscompaniesdeals have

---

tap_hubspot/hubspot.py

De 1022 use the old way of how we get companies

---

tap_hubspot/hubspot.py

Do not get all properties to avoid Client Error: URI Too Long for url

---

tap_hubspot/hubspot.py

De 1076 hubspot association labels

---

tap_hubspot/hubspot.py

new field sleekflow_io

---

tap_hubspot/__init__.py

sync engagement table in the end

---

tap_hubspot/__init__.py
tap_hubspot/hubspot.py

de 1090 tap hubspot search endpoint not found

---

.vscode/launch.json
tap_hubspot/hubspot.py

de 1131 bug hubspot too many requests

---

tap_hubspot/hubspot.py

add fields cloudtalk and getmagic

---

tap_hubspot/hubspot.py

new contact field cloudtalk

---

tap_hubspot/hubspot.py

add ably_id

---

tap_hubspot/hubspot.py

new company fields for ably

---

tap_hubspot/hubspot.py

contact mrr cloudtalk

---

tap_hubspot/__init__.py
tap_hubspot/hubspot.py

de 1189 cost compute cost exploding for vault

---

tap_hubspot/hubspot.py

new field qmarkets_net

---

tap_hubspot/hubspot.py

new contacts fields for cloudtalk

---

tap_hubspot/hubspot.py

new fields cloudtalk_io

---

tap_hubspot/hubspot.py

new company field cloudtalk

---

tap_hubspot/hubspot.py

new contact field

---

tap_hubspot/hubspot.py

add industry field for ivalua

---

tap_hubspot/hubspot.py

add logmycare fields

---

tap_hubspot/hubspot.py

add field cloudtalk_io

---

tap_hubspot/__init__.py

Exit 5 on credentials error

---

tap_hubspot/hubspot.py

Add contact field monthly_recurring_revenue_only_software

---

tap_hubspot/__init__.py
tap_hubspot/hubspot.py

don't fail when the scope is missing

---

tap_hubspot/hubspot.py

add contact fields for coverflex

---

tap_hubspot/hubspot.py

Add company fields for agencyanalytics_com

---

tap_hubspot/hubspot.py

Add sign_up_date for ably_com

---

tap_hubspot/hubspot.py

add contact field

---

tap_hubspot/hubspot.py

add new fields

---

tap_hubspot/hubspot.py

add company fields trengo

---

tap_hubspot/hubspot.py

get campaign data for email events

get campaign data

---

tap_hubspot/hubspot.py

continue when there is not campaign info

---

tap_hubspot/__init__.py
tap_hubspot/hubspot.py

add note and tasks properties

---

tap_hubspot/__init__.py
tap_hubspot/hubspot.py

We need them for the event builder.

add meeting and call properties

---

tap_hubspot/__init__.py

prevent missing flag error; add log for advanced features

---

.gitignore
tap_hubspot/hubspot.py

Catching invalid credentials exception for portal id request

S 2919 hubspot failed to revoke credentials

---

tap_hubspot/hubspot.py

https://developers.hubspot.com/changelog/increasing-our-api-limits

adjust rate limit for hubspot

---

tap_hubspot/hubspot.py

Add debug log for contacts

---

tap_hubspot/hubspot.py

Raise InvalidCredentials should 403 be returned from oauth/v1/token

---

tap_hubspot/hubspot.py

Increase max_tries and max_time to increase likelihood of recovering
